### ISSUE TITLE
Link context on image link is using image URL instead of link target

### ISSUE THREAD

**Issue by scottywz** [andy-portmen/external-application-button#3] opened 2017-09-29 14:39 UTC
Using a context menu entry set to "Link context" only on a link containing an image (e.g. `<a href="<HREF>"><img src="<IMAGE>" /></a>`) is using the image URL (IMAGE) as opposed to the link URL (HREF).

Example:  any stream preview image at https://www.twitch.tv/directory/all  
Expected behavior is that the URL used should be the same as for the stream name below the image.

I believe this is a regression caused by commit 1532ca629b0c9cafd73d619c33d3a6819090af96.

**Comment by Killogy** [comment] 2017-09-29 19:08
I confirm this with Versión 0.2.4 any context option combination.

Versión 0.2.1 it works
Versión 0.2.3 it works only with some Context combinations, others combinations console show addon is trying to send current page URL (https://www.twitch.tv/directory/videos/all) instead Link url of the stream video.

Combinations for example with version 0.2.3:

if **Link Context** is checked it works

if **Image Context** is checked does not works

if **Link Context** + **Image Context** are checked it works

if **Link Context** + **Image Context** + **Page Context** are checked does not works

if **Link Context** + **Image Context** + **Video Context** are checked it works

if **Link Context** + **Image Context** + **Audio Context** are checked it works

if **Link Context** + **Image Context** + **Video Context** + **Audio Context** are checked it works

if **Link Context** + **Image Context** + **Video Context** + **Audio Context** + **Tab Context** are checked it works

**Comment by andy-portmen** [comment] 2017-09-30 06:34
These multiple placements are more complex than I thought! Please give the dev version a try and let me know if it works as expected or not;

https://github.com/andy-portmen/external-application-button/archive/master.zip
Download the XPI and install it. Then try all the different combinations.

To install on Chrome, open chrome://extensions, turn the developer mode on, and point the "Load unpack extension" button to the root of the extracted folder. 

Expected behaviour:
1. Link context is selected -> Returns link
2. Link + anything else -> Returns link
3. Image, video, or audio is selected -> Returns src
4. Image, video, or audio + anything except link -> Returns src
5. page selection -> Returns top URL
6. Frame selection -> Returns frame URL

To test, open the background page and check "do not warn errors". This way you get the URL in the console window without the need to actually connect to an external executable.

**Comment by Killogy** [comment] 2017-09-30 07:59
Link context is selected ->load video stream link
Link + anything else -> load video stream link
Image, video, or audio is selected ->Load thumbnail image URL (video or audio did not show any addon icon)
Image, video, or audio + anything except link -> Load thumbnail image URL

**Comment by andy-portmen** [comment] 2017-09-30 09:09
> Link context is selected ->load video stream link

Example page?

**Comment by andy-portmen** [comment] 2017-09-30 09:10
> Image, video, or audio + anything except link -> Load thumbnail image URL

Example please

**Comment by Killogy** [comment] 2017-09-30 09:11
https://www.twitch.tv/communities/varietystreaming

**Comment by andy-portmen** [comment] 2017-09-30 09:16
If I only have "link" in the placement section, I don't get any context menu over the player which is expected, so I am not able to reproduce

> Link context is selected ->load video stream link

**Comment by andy-portmen** [comment] 2017-09-30 09:21
> https://www.twitch.tv/communities/varietystreaming

If I select video, audio and image, still I don't get any context menu over the player as the player does not have a src attribute (or it does not allow sharing)

This is an example of open video; https://www.w3schools.com/html/html5_video.asp

**Comment by Killogy** [comment] 2017-09-30 09:37
If link context is checked, right clicking on thumbnail image I get the context menu to send to external player and addon send stream URLto  play video stream properly.

By visiting video stream page, I don´t get link context option. it´s ok. 

On https://www.w3schools.com/html/html5_video.asp If Video context is checked only, I get context menu option to send to external player, reproduces properly. If Video+image+audio is checked, I get context menu too and send video stream to external player properly

**Comment by Killogy** [comment] 2017-09-30 11:32
On https://www.twitch.tv/communities/varietystreaming if image context is checked and I click on thumbnail image, addon send to external player the image URL https://static-cdn.jtvnw.net/previews-ttv/live_user_burkeblack-320x180.jpg instead link URL behind thumbnail image https://www.twitch.tv/burkeblack. It is this the expected behaviour with image context?

If image + link context is checked or link context is checked only , addon send URL behind thumbnail image https://www.twitch.tv/burkeblack same URL as clicking on Link below thumbnail image **Lizardmen [Hard] 💀Ryzen 7 Giveawa...**

**Comment by andy-portmen** [comment] 2017-09-30 11:46
> if image context is checked and I click on thumbnail image, addon send to external player the image URL

That seems rational to me. When the "image", "audio", or "video" contexts are the only available ones, the extension will use the "src" attribute; however, if "link" context is also selected, the extension uses "href" attribute instead. This is what I am proposing in https://github.com/andy-portmen/external-application-button/issues/3#issuecomment-333287971

> If image + link context is checked or link context is checked only , addon send URL behind thumbnail 

This seems rational too.

> So if user scottywz wants to send the video stream to external player, he must to check link context option, instead image context, so clicking on thumbnail image addon will send the video stream URL instead static image URL

Right, the "link" context needs to be included.

I think this new arrangement can handle most cases. If so I can submit the new version. I'll wait till tomorrow to test more

**Comment by Killogy** [comment] 2017-09-30 12:13
So with 0.2.4 if link context is checked, right clicking on thumbnail image, menu context icon appear and addon is sending image URL instead stream URL.

Thumbnails on https://www.twitch.tv/ are a combination between image+link so that´s because if only Link context is checked, clicking on Thumbnail the context menu icon to send to external player appear, the problem is that addon is sending static image URL of the Thumbnail instead the URLof the  video stream behind the Thumbnail.

If only image context is checked, the addon send image URL of the Thumbnail. that´s correct. 

So because Thumbnail got a link to the stream video, **link context option** must to be checked instead image context option.

Image context will send image URL and Link context will send link of the stream video. Right now, with 0.2.4 **link context** is sending image URL of the Thumbnail instead link of the stream video.

**Comment by andy-portmen** [comment] 2017-09-30 12:25
0.2.4 has a problem with image, video and audio contexts (src attribute the highest priority). The dev version of https://github.com/andy-portmen/external-application-button/issues/3#issuecomment-333287971 fixes this issue and is working as the proposal.

**Comment by BlueMax** [comment] 2017-10-01 21:28
Firefox 55.0.3 + External Application Button 0.25
Bug is fixed here. Thanks!

**Closed** 2018-09-24 11:39 UTC
